### PR TITLE
Perfdata fix plus mocking fix

### PR DESCRIPTION
**Pull request by elementalvoid**
Hello there. I'm creating this PR to see if you're interested in these fixes. I had to make them in order to successfully release our new checks using the naghelp tools. If you're interested but would like some fixups just let me know. For the most part everything has been great; I only had two minor issues.

First, running unit tests was problematic because naghelp attempts to exit when the response if sent. It order to create unit tests for my checks I had to replace the`response.ResponseLevel` `exit` method with a dummy/noop method. However, this meant that the plugin.run function would fall through to a safety check outside of the main try/catch logic. Since that safety check changes the response level of the check it invalidated my unit test's check against the expected response level. I simply removed the safety check. Maybe you have a better way?

Second, my Nagios installation was not properly parsing the perfdata output. I looked back at the perfdata spec and found that the current output of the plugin response was overly complex. I simplified it by printing all perfdata at once. Now my installation properly parses the data.

### CODE REVIEW

**Comment by elementalvoid** [comment]
In case you're curious, here's a skeleton of what I am doing for my unit tests. It's pretty basic but it allowed me to develop the entire check without actually connecting to any real servers.

``` python
import sys
from unittest import TestCase

from mocket.mocket import mocketize, Mocket, MocketEntry
from mock import patch

from naghelp.response import OK, ResponseLevel

from plugin_commons import WayinPlugin


def dummy(self):
    return

status_outputs = [ 'list of', 'status', 'json outputs', 'from real server']


class TestCheckName(TestCase):
    host = "localhost"
    ip = '127.0.0.1'
    port = 8080

    @mocketize
    @patch.object(ResponseLevel, 'exit', dummy)
    def setUp(self):
        # Setup the mock socket response
        # TODO: Pull this out as a pytest fixture with params
        Mocket.register(MocketEntry((self.ip, self.port), [status_outputs[0]))
        # Qualify the plugin name
        plugin_name = WayinPlugin.plugins_basemodule + \
            'check_module.CheckName'

        # Configure sys.argv
        argv = [plugin_name,
                '--ip', self.ip,
                '--name', self.host,
                '--port', self.port,
                ]
        sys.argv = argv

        # Load and run the plugin
        self.plugin = WayinPlugin.get_instance(plugin_name)
        self.plugin.run()

    def test_collect_data(self):
        assert 'consumers' in self.plugin.data.raw

    def test_parse_data(self):
        assert 'consumers' in self.plugin.data.status

    def test_build_response(self):
        assert self.plugin.response.level is not None
        assert self.plugin.response.level == OK
        assert len(self.plugin.response.perf_items) == 2
```

**Comment by elapouya** [comment]
Hello,

For the perf data, I do not use them yet, but in nagios documentation, one should put ONE perf data on first line, then the others at the output ending after a pipe symbol.

For the unittests, you are right, there no option yet to avoid exit : I plan to add it soon.

**Comment by elementalvoid** [comment]
Thanks for the quick response.

Here's the relevant excerpt from the [Nagios plugin guidelines](http://nagios-plugins.org/doc/guidelines.html#AEN200):

> Nagios 3 and newer will concatenate the parts following a "|" in a) the first line output by the plugin, and b) in the second to last line, into a string it passes to whatever performance data processing it has configured. (Note that it currently does not insert additional whitespace between both, so the plugin needs to provide some to prevent the last pair of a) and the first of b) getting run together.)

Nagios will _concatenate_ the first and last line's perfdata elements together. That is, you can use strictly the first line, strictly the second line, or both. Nagios does not require that more than one perfdata entries be split across the first and last lines. It is fully supported to print all perfdata on the first line. The only reason one would normally choose to split them is for brevity on the first line.

The more important piece is the "note" in the parenthesis. It states that Nagios simply concatenates the parts following a "|" together; it does not ensure that any space is inserted between them. This is actually the reason the perfdata fails to process as currently formatted. The first and second perfdata entries output by the response will not be space separated and thus Nagios will not be able to parse them.

Given both of those things I chose to simplify the output and just print all perfdata at the same time. If you'd prefer I'll keep the first and last line printing but force some whitespace to be included to allow for proper parsing.

Regarding the unit testing: Just let me know and I'll be happy to pull this bit out. I'll maintain my fork until such time as you add support.

**Comment by elapouya** [comment]
Well, yes, I would prefer to keep the first and last line printing but
force some whitespace to be included to allow for proper parsing.

2016-07-25 23:51 GMT+02:00 Matt Klich notifications@github.com:

**Comment by elementalvoid** [comment]
Created a new PR #2 for just the perfdata fix. Closing this one.

**Pull request closed without merging**
